version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: kittens_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kittens_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
