@baseUrl = http://localhost:8080
@kittensPath = /api/kittens
@searchEndpoint = {{baseUrl}}{{kittensPath}}/search
@getByIdEndpoint = {{baseUrl}}{{kittensPath}}/1

###

GET {{baseUrl}}{{kittensPath}}
Accept: text/plain

###

GET {{getByIdEndpoint}}
Accept: application/json

###

POST {{searchEndpoint}}?page=0&size=5
Content-Type: application/json
Accept: application/json

{}

###

POST {{searchEndpoint}}?page=0&size=5
Content-Type: application/json
Accept: application/json

{
  "name": "Salem"
}

###

POST {{searchEndpoint}}?page=0&size=5
Content-Type: application/json
Accept: application/json

{
  "breeds": ["SIBERIAN"]
}

###

POST {{searchEndpoint}}?page=0&size=5
Content-Type: application/json
Accept: application/json

{
  "minPurr": 2,
  "maxPurr": 9
}

###

POST {{searchEndpoint}}?page=0&size=5
Content-Type: application/json
Accept: application/json

{
  "ownerIds": [1]
}
