spring:
  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/kittens_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: ${JWT_SECRET} # should be configured in .env file!
  expiration: 3600000   # 1h in ms
