spring:
  main:
    allow-bean-definition-overriding: true

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/kittens_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  # should be configured in .env file!
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
