services:
  postgres:
    image: postgres:15-alpine
    container_name: kittens_demo
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kittens_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
