spring:
  main:
    allow-bean-definition-overriding: true

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://postgres-kitten:5432/kitten_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    ru.kimvlry.kittens: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"