spring:
  main:
    allow-bean-definition-overriding: true

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/kittens_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  access_token_expiration: ${JWT_ACCESS_EXPIRATION}
  refresh_token_expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    root: INFO
    ru.kimvlry.kittens: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
